
name: Install Apollo Rover
inputs:
  apollo-key:
    required: true

runs:
  using: "composite"
  steps:
  - name: Install Rover
    shell: bash
    run: |
      curl -sSL https://rover.apollo.dev/nix/v0.1.0 | sh
      echo "$HOME/.rover/bin" >> $GITHUB_PATH
env:
  APOLLO_KEY: ${{inputs.APOLLO_KEY}}
  APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
